/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ismavbot;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void appHasAGreeting() {
        application classUnderTest = new application("token");
        assertNotNull(classUnderTest);
    }
}
